import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  tela: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  conteudo: {
    paddingBottom: 40,
  },
  cabecalho: {
    backgroundColor: '#1D4ED8',
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
  },
  cabecalhoTitulo: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: '800',
  },
  cabecalhoSubtitulo: {
    color: '#BFDBFE',
    fontSize: 14,
    marginTop: 4,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 18,
    marginHorizontal: 16,
    marginTop: 16,
  },
  tituloSecao: {
    color: '#1E293B',
    fontSize: 18,
    fontWeight: '700',
    marginHorizontal: 16,
    marginTop: 24,
    marginBottom: 10,
  },
  tituloFormulario: {
    color: '#1E293B',
    fontSize: 17,
    fontWeight: '700',
    marginTop: 22,
    marginBottom: 12,
  },
  rotuloCampo: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 10,
    marginBottom: 7,
  },
  input: {
    minHeight: 50,
    color: '#0F172A',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 15,
  },
  linhaTipos: {
    flexDirection: 'row',
    gap: 10,
  },
  botaoTipo: {
    flex: 1,
    minHeight: 46,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  botaoTipoSelecionado: {
    backgroundColor: '#DBEAFE',
    borderColor: '#1D4ED8',
  },
  textoTipo: {
    color: '#475569',
    fontWeight: '600',
  },
  textoTipoSelecionado: {
    color: '#1D4ED8',
  },
  botaoPrimario: {
    minHeight: 52,
    backgroundColor: '#1D4ED8',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    marginTop: 20,
    paddingHorizontal: 18,
  },
  botaoAdicionar: {
    minHeight: 48,
    backgroundColor: '#1D4ED8',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
  },
  botaoSecundario: {
    minHeight: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#1D4ED8',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 16,
    marginTop: 12,
    paddingHorizontal: 18,
  },
  textoBotaoPrimario: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  textoBotaoSecundario: {
    color: '#1D4ED8',
    fontSize: 16,
    fontWeight: '700',
  },
  cardParada: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 10,
  },
  numeroParada: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#DBEAFE',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  numeroParadaTexto: {
    color: '#1D4ED8',
    fontWeight: '800',
  },
  dadosParada: {
    flex: 1,
  },
  tipoParada: {
    color: '#1D4ED8',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  destinatario: {
    color: '#1E293B',
    fontSize: 16,
    fontWeight: '700',
    marginTop: 3,
  },
  endereco: {
    color: '#64748B',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  remover: {
    color: '#DC2626',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 10,
  },
  estadoVazio: {
    color: '#64748B',
    fontSize: 14,
    textAlign: 'center',
  },
  cardMotorista: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 15,
    marginHorizontal: 16,
    marginBottom: 10,
  },
  cardMotoristaSelecionado: {
    borderColor: '#1D4ED8',
    backgroundColor: '#EFF6FF',
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#1D4ED8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  avatarTexto: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  dadosMotorista: {
    flex: 1,
  },
  nomeMotorista: {
    color: '#1E293B',
    fontSize: 15,
    fontWeight: '700',
  },
  veiculo: {
    color: '#64748B',
    fontSize: 13,
    marginTop: 3,
  },
  disponivel: {
    color: '#15803D',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  radio: {
    width: 22,
    height: 22,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    borderRadius: 11,
  },
  radioSelecionado: {
    borderWidth: 7,
    borderColor: '#1D4ED8',
  },
});