import {StyleSheet} from 'react-native';

export const cores = {
  primaria: '#1D4ED8',
  primariaClara: '#DBEAFE',
  fundo: '#F8FAFC',
  card: '#FFFFFF',
  texto: '#172033',
  textoSuave: '#64748B',
  borda: '#E2E8F0',
  sucesso: '#15803D',
  sucessoFundo: '#DCFCE7',
  alerta: '#B45309',
  alertaFundo: '#FEF3C7',
  perigo: '#DC2626',
  perigoFundo: '#FEE2E2',
  roxo: '#7E22CE',
  roxoFundo: '#F3E8FF',
};

export const estilos = StyleSheet.create({
  areaSegura: {flex: 1, backgroundColor: cores.primaria},
  tela: {flex: 1, backgroundColor: cores.fundo},
  conteudo: {padding: 16, paddingBottom: 104},
  centro: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: cores.fundo,
  },
  cabecalho: {
    backgroundColor: cores.primaria,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  cabecalhoLinha: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cabecalhoTitulo: {color: '#FFFFFF', fontSize: 24, fontWeight: '800'},
  cabecalhoSubtitulo: {color: '#BFDBFE', fontSize: 14, marginTop: 4},
  voltar: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    paddingVertical: 8,
    paddingRight: 14,
  },
  titulo: {color: cores.texto, fontSize: 25, fontWeight: '800'},
  subtitulo: {
    color: cores.textoSuave,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 6,
  },
  tituloSecao: {
    color: cores.texto,
    fontSize: 18,
    fontWeight: '800',
    marginTop: 22,
    marginBottom: 10,
  },
  card: {
    backgroundColor: cores.card,
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
  },
  cardAzul: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 18,
    padding: 18,
    marginBottom: 12,
  },
  linha: {flexDirection: 'row', alignItems: 'center'},
  linhaEntre: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  flex: {flex: 1},
  rotulo: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 6,
  },
  valor: {color: cores.texto, fontSize: 16, fontWeight: '700'},
  texto: {color: cores.textoSuave, fontSize: 14, lineHeight: 21},
  input: {
    minHeight: 50,
    color: cores.texto,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 15,
    marginBottom: 10,
  },
  inputMultilinha: {minHeight: 88, textAlignVertical: 'top', paddingTop: 14},
  botao: {
    minHeight: 52,
    backgroundColor: cores.primaria,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    marginTop: 12,
  },
  botaoTexto: {color: '#FFFFFF', fontSize: 16, fontWeight: '800'},
  botaoSecundario: {
    minHeight: 50,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: cores.primaria,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    marginTop: 10,
  },
  botaoSecundarioTexto: {
    color: cores.primaria,
    fontSize: 15,
    fontWeight: '800',
  },
  botaoPerigo: {borderColor: cores.perigo},
  botaoPerigoTexto: {color: cores.perigo},
  botaoDesabilitado: {opacity: 0.45},
  grade: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  metrica: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 16,
    padding: 14,
  },
  metricaNumero: {color: cores.primaria, fontSize: 24, fontWeight: '800'},
  metricaTexto: {color: cores.textoSuave, fontSize: 12, marginTop: 4},
  badge: {
    alignSelf: 'flex-start',
    borderRadius: 99,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  badgeTexto: {fontSize: 12, fontWeight: '800'},
  paradaNumero: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: cores.primariaClara,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  paradaNumeroTexto: {color: cores.primaria, fontWeight: '800'},
  separador: {height: 1, backgroundColor: cores.borda, marginVertical: 14},
  abas: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: cores.borda,
    paddingBottom: 8,
    paddingTop: 8,
  },
  aba: {flex: 1, alignItems: 'center', paddingVertical: 7},
  abaTexto: {color: cores.textoSuave, fontSize: 11, fontWeight: '700'},
  abaTextoAtiva: {color: cores.primaria},
  progressoFundo: {
    height: 9,
    borderRadius: 5,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
    marginTop: 10,
  },
  progresso: {height: 9, borderRadius: 5, backgroundColor: cores.primaria},
  opcao: {
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  opcaoAtiva: {borderColor: cores.primaria, backgroundColor: '#EFF6FF'},
  opcaoTexto: {color: cores.texto, fontWeight: '700'},
  logo: {
    width: 78,
    height: 78,
    borderRadius: 24,
    backgroundColor: cores.primaria,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  logoTexto: {color: '#FFFFFF', fontSize: 27, fontWeight: '900'},
  marca: {color: cores.texto, fontSize: 34, fontWeight: '900'},
  marcaAzul: {color: cores.primaria},
  link: {
    color: cores.primaria,
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: 10,
    textAlign: 'center',
  },
  sucessoIcone: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: cores.sucessoFundo,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  sucessoIconeTexto: {color: cores.sucesso, fontSize: 34, fontWeight: '900'},
  assinatura: {
    height: 190,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#94A3B8',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 14,
  },
  assinaturaTexto: {color: cores.texto, fontSize: 28, fontStyle: 'italic'},
  foto: {
    height: 190,
    borderRadius: 16,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 14,
  },
  fotoTexto: {color: cores.textoSuave, fontSize: 15, fontWeight: '700'},
  contador: {
    color: cores.textoSuave,
    fontSize: 13,
    textAlign: 'center',
    marginTop: 10,
  },
  textoCentral: {textAlign: 'center'},
  larguraTotalTopo18: {width: '100%', marginTop: 18},
  marcaContainer: {alignItems: 'center', marginVertical: 22},
  espacadorHorizontal: {width: 10},
  margemEsquerda10: {marginLeft: 10},
  margemTopo4: {marginTop: 4},
  margemTopo8: {marginTop: 8},
  margemTopo10: {marginTop: 10},
  margemTopo18: {marginTop: 18},
});
