import {StyleSheet} from 'react-native';

export const cores = {
  primaria: '#1D4ED8',
  primariaClara: '#DBEAFE',
  fundo: '#F8FAFC',
  card: '#FFFFFF',
  texto: '#172033',
  textoSuave: '#64748B',
  borda: '#E2E8F0',
  sucesso: '#15803D',
  sucessoFundo: '#DCFCE7',
  alerta: '#B45309',
  alertaFundo: '#FEF3C7',
  perigo: '#DC2626',
  perigoFundo: '#FEE2E2',
  roxo: '#7E22CE',
  roxoFundo: '#F3E8FF',
  // Papéis do Material Design 3 com contraste alto (uso sob sol forte).
  primariaPressionada: '#1E40AF',
  textoSobrePrimaria: '#DBEAFE',
  textoForte: '#0F172A',
  textoApoio: '#475569',
  contorno: '#64748B',
  erro: '#B91C1C',
  // Acento "Sinal" (design system, S1): reservado para "o que fazer agora". Nunca para erro.
  acento: '#F97316',
  acentoTexto: '#C2410C',
  acentoClaro: '#FFEDD5',
};

export const estilos = StyleSheet.create({
  areaSegura: {flex: 1, backgroundColor: cores.primaria},
  tela: {flex: 1, backgroundColor: cores.fundo},
  conteudo: {padding: 16, paddingBottom: 104},
  centro: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: cores.fundo,
  },
  cabecalho: {
    backgroundColor: cores.primaria,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  cabecalhoLinha: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cabecalhoTitulo: {color: '#FFFFFF', fontSize: 24, fontWeight: '800'},
  cabecalhoSubtitulo: {color: '#BFDBFE', fontSize: 14, marginTop: 4},
  voltar: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    paddingVertical: 8,
    paddingRight: 14,
  },
  titulo: {color: cores.texto, fontSize: 25, fontWeight: '800'},
  subtitulo: {
    color: cores.textoSuave,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 6,
  },
  tituloSecao: {
    color: cores.texto,
    fontSize: 18,
    fontWeight: '800',
    marginTop: 22,
    marginBottom: 10,
  },
  card: {
    backgroundColor: cores.card,
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
  },
  cardAzul: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 18,
    padding: 18,
    marginBottom: 12,
  },
  linha: {flexDirection: 'row', alignItems: 'center'},
  linhaEntre: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  flex: {flex: 1},
  rotulo: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 6,
  },
  valor: {color: cores.texto, fontSize: 16, fontWeight: '700'},
  texto: {color: cores.textoSuave, fontSize: 14, lineHeight: 21},
  input: {
    minHeight: 50,
    color: cores.texto,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 15,
    marginBottom: 10,
  },
  inputMultilinha: {minHeight: 88, textAlignVertical: 'top', paddingTop: 14},
  botao: {
    minHeight: 52,
    backgroundColor: cores.primaria,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    marginTop: 12,
  },
  botaoTexto: {color: '#FFFFFF', fontSize: 16, fontWeight: '800'},
  botaoSecundario: {
    minHeight: 50,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: cores.primaria,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    marginTop: 10,
  },
  botaoSecundarioTexto: {
    color: cores.primaria,
    fontSize: 15,
    fontWeight: '800',
  },
  botaoPerigo: {borderColor: cores.perigo},
  botaoPerigoTexto: {color: cores.perigo},
  botaoDesabilitado: {opacity: 0.45},
  grade: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  metrica: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 16,
    padding: 14,
  },
  metricaNumero: {color: cores.primaria, fontSize: 24, fontWeight: '800'},
  metricaTexto: {color: cores.textoSuave, fontSize: 12, marginTop: 4},
  badge: {
    alignSelf: 'flex-start',
    borderRadius: 99,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  badgeTexto: {fontSize: 12, fontWeight: '800'},
  paradaNumero: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: cores.primariaClara,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  paradaNumeroTexto: {color: cores.primaria, fontWeight: '800'},
  separador: {height: 1, backgroundColor: cores.borda, marginVertical: 14},
  abas: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: cores.borda,
    paddingBottom: 8,
    paddingTop: 8,
  },
  aba: {flex: 1, alignItems: 'center', paddingVertical: 7},
  abaTexto: {color: cores.textoSuave, fontSize: 11, fontWeight: '700'},
  abaTextoAtiva: {color: cores.primaria},
  progressoFundo: {
    height: 9,
    borderRadius: 5,
    backgroundColor: '#E2E8F0',
    overflow: 'hidden',
    marginTop: 10,
  },
  progresso: {height: 9, borderRadius: 5, backgroundColor: cores.primaria},
  opcao: {
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  opcaoAtiva: {borderColor: cores.primaria, backgroundColor: '#EFF6FF'},
  opcaoTexto: {color: cores.texto, fontWeight: '700'},
  logo: {
    width: 78,
    height: 78,
    borderRadius: 24,
    backgroundColor: cores.primaria,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  logoTexto: {color: '#FFFFFF', fontSize: 27, fontWeight: '900'},
  marca: {color: cores.texto, fontSize: 34, fontWeight: '900'},
  marcaAzul: {color: cores.primaria},
  erroFormulario: {
    color: cores.perigo,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 10,
    textAlign: 'center',
  },
  link: {
    color: cores.primaria,
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: 10,
    textAlign: 'center',
  },
  sucessoIcone: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: cores.sucessoFundo,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  sucessoIconeTexto: {color: cores.sucesso, fontSize: 34, fontWeight: '900'},
  assinatura: {
    height: 190,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#94A3B8',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 14,
  },
  assinaturaTexto: {color: cores.texto, fontSize: 28, fontStyle: 'italic'},
  assinaturaCanvas: {
    height: 190,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#94A3B8',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    marginVertical: 14,
  },
  assinaturaPreview: {width: '100%', height: '100%', resizeMode: 'contain'},
  foto: {
    height: 190,
    borderRadius: 16,
    backgroundColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 14,
    overflow: 'hidden',
  },
  fotoTexto: {color: cores.textoSuave, fontSize: 15, fontWeight: '700'},
  fotoPreview: {width: '100%', height: '100%', resizeMode: 'cover'},
  contador: {
    color: cores.textoSuave,
    fontSize: 13,
    textAlign: 'center',
    marginTop: 10,
  },
  textoCentral: {textAlign: 'center'},
  larguraTotalTopo18: {width: '100%', marginTop: 18},
  marcaContainer: {alignItems: 'center', marginVertical: 22},
  espacadorHorizontal: {width: 10},
  margemEsquerda10: {marginLeft: 10},
  margemTopo4: {marginTop: 4},
  margemTopo8: {marginTop: 8},
  margemTopo10: {marginTop: 10},
  margemTopo18: {marginTop: 18},

  // Tela de login (Material Design 3): faixa da marca + folha do formulário.
  loginRolagem: {flex: 1, backgroundColor: cores.primaria},
  loginRolagemConteudo: {flexGrow: 1},
  loginFaixa: {paddingHorizontal: 24, paddingTop: 40, paddingBottom: 56},
  loginFaixaComVoltar: {paddingTop: 8},
  loginVoltar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginLeft: -12,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginVoltarPressionado: {backgroundColor: 'rgba(255, 255, 255, 0.16)'},
  // Indicador de etapas do cadastro, desenhado sobre a faixa azul.
  loginProgresso: {flexDirection: 'row', gap: 6, marginTop: 20},
  loginProgressoSegmento: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
  },
  loginProgressoSegmentoAtivo: {backgroundColor: '#FFFFFF'},
  loginProgressoTexto: {
    color: cores.textoSobrePrimaria,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    marginTop: 8,
  },
  loginMarcaLinha: {flexDirection: 'row', alignItems: 'center', gap: 12},
  loginMarca: {
    color: '#FFFFFF',
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
  },
  loginSlogan: {
    color: cores.textoSobrePrimaria,
    fontSize: 16,
    lineHeight: 24,
    marginTop: 8,
  },
  loginFolha: {
    flex: 1,
    backgroundColor: cores.card,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -28,
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 24,
    elevation: 1,
  },
  loginTitulo: {
    color: cores.textoForte,
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '600',
  },
  loginApoio: {
    color: cores.textoApoio,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
    marginBottom: 8,
  },
  loginRotulo: {
    color: cores.textoForte,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
    marginTop: 16,
    marginBottom: 6,
  },
  loginCampo: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: cores.card,
    borderWidth: 1,
    borderColor: cores.contorno,
    borderRadius: 12,
    paddingLeft: 16,
  },
  // Borda de 2dp no foco; o padding compensa para o conteúdo não pular.
  loginCampoFocado: {borderWidth: 2, borderColor: cores.primaria, paddingLeft: 15},
  loginCampoTexto: {
    flex: 1,
    minHeight: 54,
    color: cores.textoForte,
    fontSize: 16,
    marginLeft: 12,
    paddingVertical: 0,
  },
  loginCampoTextoSemAcao: {marginRight: 16},
  loginCampoCodigo: {fontSize: 22, fontWeight: '600', letterSpacing: 6},
  loginAcaoCampo: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  loginErro: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: cores.perigoFundo,
    borderRadius: 12,
    padding: 12,
    marginTop: 16,
  },
  loginErroTexto: {
    flex: 1,
    color: cores.erro,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  // Variante informativa da faixa de erro (ex.: aviso de demonstração).
  loginAviso: {backgroundColor: cores.primariaClara, marginTop: 0},
  loginAvisoTexto: {color: cores.primariaPressionada},
  loginBotao: {
    minHeight: 56,
    borderRadius: 28,
    backgroundColor: cores.primaria,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    marginTop: 24,
  },
  loginBotaoPressionado: {backgroundColor: cores.primariaPressionada},
  loginBotaoTexto: {
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
  },
  loginLink: {
    minHeight: 48,
    alignSelf: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginTop: 8,
  },
  loginLinkTexto: {
    color: cores.primaria,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  loginEspacador: {flexGrow: 1, minHeight: 24},
  loginDivisor: {flexDirection: 'row', alignItems: 'center', gap: 12},
  loginDivisorLinha: {flex: 1, height: 1, backgroundColor: cores.borda},
  loginDivisorTexto: {color: cores.textoApoio, fontSize: 14, lineHeight: 20},
  loginBotaoContornado: {
    minHeight: 56,
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: cores.primaria,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    marginTop: 16,
  },
  loginBotaoContornadoPressionado: {backgroundColor: cores.primariaClara},
  loginBotaoContornadoTexto: {
    color: cores.primaria,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
  },
  botaoConteudo: {flexDirection: 'row', alignItems: 'center', gap: 8},
  botaoContornadoPerigo: {borderColor: cores.contorno},
  botaoContornadoPerigoPressionado: {backgroundColor: cores.perigoFundo},
  botaoContornadoPerigoTexto: {color: cores.erro},

  // Navigation Bar do MD3: 80dp (12 + pílula 32 + 4 + rótulo 16 + 16) + margem do sistema.
  navegacao: {
    flexDirection: 'row',
    backgroundColor: cores.card,
    borderTopWidth: 1,
    borderTopColor: cores.borda,
    paddingTop: 12,
  },
  navegacaoItem: {flex: 1, minHeight: 52, alignItems: 'center', gap: 4},
  navegacaoItemPressionado: {opacity: 0.6},
  // Indicador ativo: pílula 64x32 atrás do ícone (a aba ativa não depende só da cor).
  navegacaoIndicador: {
    width: 64,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navegacaoIndicadorAtivo: {backgroundColor: cores.primariaClara},
  navegacaoRotulo: {
    color: cores.textoApoio,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  navegacaoRotuloAtivo: {color: cores.textoForte, fontWeight: '600'},

  // Área logada: seções, cards e métricas sobre a folha branca.
  telaComNavegacao: {flex: 1, backgroundColor: cores.card},
  // Fundo opaco atrás das transições (evita revelar o azul da área segura no fade).
  fundoTransicao: {flex: 1, backgroundColor: cores.card},
  secaoRotulo: {
    color: cores.textoForte,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    marginBottom: 12,
  },
  secaoRotuloAfastado: {marginTop: 32},
  cartao: {
    backgroundColor: cores.card,
    borderWidth: 1,
    borderColor: cores.borda,
    borderRadius: 16,
    padding: 16,
  },
  cartaoPressionado: {backgroundColor: cores.fundo},
  // Próxima parada: superfície preenchida, sem borda, com o endereço como informação principal.
  cartaoParada: {backgroundColor: '#F1F5F9', borderRadius: 20, padding: 20},
  paradaContexto: {
    color: cores.textoApoio,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  paradaDestinatario: {
    color: cores.textoForte,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '700',
    marginTop: 4,
  },
  paradaEndereco: {
    color: cores.textoForte,
    fontSize: 16,
    lineHeight: 24,
    marginTop: 2,
  },
  paradaJanela: {flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 12},
  cartaoTitulo: {
    flex: 1,
    color: cores.textoForte,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600',
    marginRight: 12,
  },
  textoApoio: {color: cores.textoApoio, fontSize: 14, lineHeight: 20},
  textoApoioForte: {
    color: cores.textoApoio,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '500',
  },
  linhaIcone: {flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4},
  progressoLinha: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginTop: 16,
  },
  progressoPercentual: {
    color: cores.primaria,
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '700',
  },
  metricasLinha: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: cores.borda,
    marginTop: 16,
    paddingTop: 12,
  },
  metricaItem: {flex: 1},
  metricaDivisor: {width: 1, backgroundColor: cores.borda, marginHorizontal: 12},
  metricaValor: {
    color: cores.textoForte,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
  },
  metricaRotulo: {color: cores.textoApoio, fontSize: 12, lineHeight: 16},
  iconeCirculo: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: cores.primariaClara,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },

  // Perfil: avatar com iniciais e linhas de informação.
  perfilCabecalho: {flexDirection: 'row', alignItems: 'center', gap: 16},
  perfilAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  perfilIniciais: {
    color: cores.primaria,
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700',
  },
  perfilNome: {
    color: '#FFFFFF',
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '700',
  },
  perfilLinha: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    minHeight: 64,
    paddingVertical: 8,
  },
  perfilSeparador: {height: 1, backgroundColor: cores.borda, marginLeft: 40},
  perfilValor: {color: cores.textoForte, fontSize: 16, lineHeight: 24},
  perfilRodape: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 24,
  },
  perfilRodapeTexto: {color: cores.textoApoio, fontSize: 12, lineHeight: 16},
});
